apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: echoserver-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver-application
  template:
    metadata:
      labels:
        app: echoserver-application
    spec:
      containers:
      - image: e2eteam/echoserver
        imagePullPolicy: Always
        name: echoserver-application
        ports:
        - containerPort: 8080
