apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: echoserver-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver-application
  template:
    metadata:
      labels:
        app: echoserver-application
    spec:
      containers:
      #- image: opsdockerimage/echoserver:1.10 
      - image: e2eteam/2.2-linux-arm64:2.2
        imagePullPolicy: Always
        name: echoserver-application
        ports:
        - containerPort: 8080
